FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update
RUN apt -y upgrade
RUN apt install sudo -y
RUN apt install curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
RUN apt -y install nodejs
RUN node --version
RUN npm --version

COPY . ./deltachat/
WORKDIR ./deltachat
RUN ls