FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install npm

RUN ls
RUN pwd
RUN mkdir app
COPY . ./app/
WORKDIR ./app
RUN ls
RUN pwd
RUN npm install
RUN npm start